[window]
x = -150
y = -430
w = 100
h = 100

click_through = true
update_interval_seconds = 1

[cursor-transparency]
enabled = true
polling_interval_seconds = 0.1
opacity = 0.0 # 0.0 is fully transparent, 1.0 is fully opaque
inner_radius = 50 # if the cursor is within this radius, the clock will have opacity given
outer_radius = 200 # if the cursor is further than this radius, the clock will be fully opaque
# the opacity should scale linearly from 1 to (given opacity variable) between the inner and outer radius.